apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-platform-lcm.fullname" . }}
  labels:
    {{- include "k8s-platform-lcm.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-platform-lcm.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-platform-lcm.fullname" . }}
  namespace: {{ .Release.Namespace }}
