apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-platform-lcm.fullname" . }}
  labels:
    {{- include "k8s-platform-lcm.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  {{- include "k8s-platform-lcm.clusterRole.resources" . | indent 2 }}
  verbs: ["get", "list"]