apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-platform-lcm.fullname" . }}
  labels:
    {{- include "k8s-platform-lcm.labels" . | nindent 4 }}
  {{- with .Values.deployAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  # file-like keys
  config.yml: |-
    {{- if .Values.config }}
    {{ .Values.config | nindent 4 }}
    {{- end }}