apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-platform-lcm.serviceAccountName" . }}
  labels:
    {{- include "k8s-platform-lcm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
