project_name: k8s-platform-lcm

before:
  hooks:
    - go mod download

builds:
- 
  env:
    - CGO_ENABLED=0
  main: ./cmd/lcm/main.go  
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64

archives:
- 
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  files:
    - README.md
    - LICENSE
    - exampleConfig.yaml
    - templates/*

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true