project_name: k8s-platform-lcm

before:
  hooks:
    - go mod download

builds:
-
  env:
    - CGO_ENABLED=0
  main: ./cmd/lcm/main.go  
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64

archives:
-
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  files:
    - README.md
    - LICENSE
    - exampleConfig.yaml
    - templates/*
    - static/*

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

dockers:
-
  image_templates:
    - "arminc/lcm:latest"
    - "arminc/lcm:{{ .Tag }}"
  build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  extra_files:
    - templates
    - static