language: go

env: GO111MODULE=on

go:
  - 1.13.x

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - golangci-lint run
  - go test ./...
  - ./build.sh

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    file:
      - dist/lcm-$TRAVIS_TAG-darwin
      - dist/lcm-$TRAVIS_TAG-linux
      - dist/lcm-$TRAVIS_TAG-windows
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script:
      docker push arminc/lcm:$TRAVIS_TAG &&
      docker push arminc/lcm:latest
    on:
      tags: true