---

dictionaries:
  - en

excluded_files:
  - go.mod
  - go.sum

excluded_words:
  - repo
  - repos
  - sirupsen
  - logrus
  - gitHubRepos
  - NewRepoVersionGetter
  - Warnf
  - Errorf
  - rerr
  - aerr
  - stretchr
  - SemVer
  - FindHighestSemVer
  - TestHighestPre
  - TestHighestPreAndBuild
  - pre
  - TestHighestNotSemVer
  - containerd
  - Cves
  - Debugf
  - GetCves
  - cve
  - golangci-lint
  - Severities
  - Itoa
  - strconv

spellcheck_filenames: true