---

dictionaries:
  - en

excluded_files:
  - go.mod
  - go.sum

excluded_words:
  - repo
  - repos
  - sirupsen
  - logrus
  - gitHubRepos
  - NewRepoVersionGetter
  - Warnf
  - Errorf
  - rerr
  - aerr
  - stretchr
  - SemVer
  - FindHighestSemVer
  - TestHighestPre
  - TestHighestPreAndBuild
  - pre
  - TestHighestNotSemVer
  - containerd
  - Cves
  - Debugf
  - GetCves
  - cve
  - golangci-lint
  - Severities
  - Itoa
  - strconv
  - hasher
  - crypto
  - Wrapf
  - deduplicated
  - Kube
  - NewKubeClient
  - apimachinery
  - gcr
  - Infof
  - kubeconfig
  - clientcmd
  - vulnera
  
spellcheck_filenames: true