---

dictionaries:
  - en

excluded_files:
  - go.mod
  - go.sum

excluded_words:
  - repo
  - repos
  - sirupsen
  - logrus
  - gitHubRepos
  - NewRepoVersionGetter
  - Warnf
  - Errorf
  - rerr
  - aerr
  - stretchr
  - SemVer
  - FindHighestSemVer
  - TestHighestPre
  - TestHighestPreAndBuild
  - pre

spellcheck_filenames: true