apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: k8s-platform-lcm
    context: cluster
  name: lcm-service-monitor
spec:
  endpoints:
    - path: /metrics
      port: lcm-metrics
      interval: 600s # 5 minutes
  selector:
    matchLabels:
      app: k8s-platform-lcm
