apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-platform-lcm
  namespace: k8s-platform-lcm
spec:
  chart:
    git: git@github.com:BlueOwlDev/k8s-platform-lcm.git
    ref: blueowl-ci
    path: k8s/chart/k8s-platform-lcm
  interval: 5m
  test:
    enable: true
    ignoreFailures: true
# Default values
  values:
    test:
      enabled: false
