apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-platform-lcm
  namespace: k8s-platform-lcm
spec:
  interval: 5m
  chart:
    spec:
      chart: ./k8s/chart/k8s-platform-lcm
      sourceRef:
        kind: GitRepository
        name: k8s-platform-lcm
        namespace: flux-system
# Default values
  values:
    initialDelaySeconds: 120
