apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-platform-lcm
  namespace: k8s-platform-lcm
spec:
  chart:
    spec:
      version: "<1.0.0"
  values:
    image:
      repository: 436196666173.dkr.ecr.us-east-1.amazonaws.com/blueowldev/k8s-platform-lcm
      tag: "24f075c8-" # {"$imagepolicy": "lcm:lcm:tag"}
    helmScan:
      enabled: true
